Replace k-means++ CPU bottleneck with a `random::discrete` prim
rapidsai/raft pull request #1039
Opened 2022-11-22 15:11 UTC by Nyrio

Currently, k-means has a CPU bottleneck in its k-means++ initialization, especially when the dataset is tall and thin. At each step of the k-means++ initialization, the distances to the closest cluster centroid are copied to the host, and candidates centroids are selected using [`std::discrete_distribution`](https://en.cppreference.com/w/cpp/numeric/random/discrete_distribution). This distribution reduces and scans the weights, which is an expensive operation if the dataset has many rows, and should be done on GPU.

For the test of this new primitive, I use a small number of weights and a large number of samples and compare the actual vs expected histogram using a tolerance of 4*sigma where sigma is the standard deviation computed from the number of samples and the smallest non-zero weight. I don't know any good way to correctly test the primitive with a very large number of weights, but I'm open to suggestions.

2022-11-22 15:26 UTC, Nyrio commented
Sorry for the absolute mess in the diff and automatic labels / review requests, but `branch-23.02` is behind `branch-22.12` by 22 commits...

2022-11-22 15:30 UTC, Nyrio commented
Reverting target branch for now to `branch-22.12` to make reviews easier.

2022-11-22 16:05 UTC, Nyrio commented
Nsight Systems timelines for comparison.

before
![2022-11-22_kmeansplusplus_before](https://user-images.githubusercontent.com/17441062/203362809-f45a9c22-e7c4-43e0-9416-11e118a9abc0.PNG)

---

after
![2022-11-22_kmeansplusplus_after](https://user-images.githubusercontent.com/17441062/203362848-a4a901b8-9e61-40c6-b8b6-53b5e858cf5f.PNG)

2022-11-23 16:38 UTC, cjnolet commented
> I don't know any good way to correctly test the primitive with a very large number of weights and a small number of samples, but I'm open to suggestions.

Could we do some little tricks here like setting most of the weights to be a very small value and then setting only a few weights to be much larger values and then comparing the unique set of sampled indices against the expected histogram to see that the unique list of indices that were sampled are all peaks in the expected histogram?

2022-11-23 16:44 UTC, cjnolet requested changes
The changes look good, though aside from adding the test for the smaller sample sizes w/ larger weights, we should add a quick usage example for the docs.

2022-11-23 16:44 UTC, cjnolet commented on cpp/include/raft/random/detail/rng_device.cuh
> +  // todo(lsugy): warp-collaborative binary search
Can you create an issue for this and reference it here?

2022-11-24 20:17 UTC, Nyrio commented on cpp/include/raft/random/rng.cuh
> + *
I've added one, please let me know if you're happy with it.

2022-11-24 20:18 UTC, Nyrio commented
I have consolidated the tests with small `sampled_len` / large `len`.

2022-11-29 19:59 UTC, cjnolet approved these changes
LGTM. I'm pre-approved, but we will need to change the target branch to 23.02 before this is merged.

2022-11-30 15:35 UTC, cjnolet commented
@gpucibot merge

2022-11-30 15:35 UTC, merged