Improvements in `matrix::gather`: test coverage, compilation errors, performance
rapidsai/raft pull request #1126
Opened 2023-01-10 16:07 UTC by Nyrio

In order to deprecate `copy_selected` from `ann_utils.cuh`, I wanted to make sure that the performance of `matrix::gather` was on par. But in the process I discovered that:

- Map transforms and conditional copy were not tested at all.
- In fact, most of the API in `gather.cuh` wasn't covered in tests and some of the functions didn't even compile.
- The same type `MatrixIteratorT` was used for the input and output iterators, which made it impossible to take advantage of custom iterators, as is needed in `kmeans_balanced` to convert the dataset from `T` to `float` and gather in a single step.
- The performance was really poor when `D` is small because the kernel assigns one block per row (so a block could be working on only 2 or 3 elements...)

This PR addresses all the aforementioned issues.

2023-01-10 16:09 UTC, Nyrio commented
Below is a comparison of before/after performance. The speedups range from 1x to 7x.

![2023-01-10_gather_if_perf](https://user-images.githubusercontent.com/17441062/211602407-06943a6c-2bf1-45b4-b484-95d7fb65fda5.png)

2023-01-19 10:25 UTC, tfeher requested changes
Hi Louis, thanks for the PR, it looks good! While we are here, could you improve a little bit the docstring of gather, I have left a few questions.

2023-01-19 12:38 UTC, Nyrio commented on cpp/include/raft/matrix/gather.cuh
>   * @brief  gather copies rows from a source matrix into a destination matrix according to a map.
I've improved the docs, let me know if you have further comments or are happy with the change. I also removed redundant overloads while I was there.

2023-01-19 13:42 UTC, Nyrio commented
I'm not sure what's up with CI but it doesn't seem to be a compiler nor test error.

2023-01-19 14:05 UTC, tfeher approved these changes
Thanks Louis for updating the doc. The PR looks good to me.

2023-01-19 14:35 UTC, cjnolet commented
@Nyrio the changes look good here. Before we merge this, can you verify that the changes to the template params don't break cuml downstream?

2023-01-19 16:04 UTC, Nyrio commented
@cjnolet There is one call to `gather_if` in cuML and it shouldn't break (actually, the only thing that can potentially break with my change is the mdspan overload if all the template args are explicitly specified).

2023-01-19 17:33 UTC, cjnolet approved these changes
LGTM

2023-01-21 20:55 UTC, cjnolet commented
/merge

2023-01-21 20:55 UTC, merged