Add L2SqrtExpanded support to ivf_flat ANN indices
rapidsai/raft pull request #1133
Opened 2023-01-10 22:38 UTC by benfred

2023-01-12 15:01 UTC, achirkin requested changes
Thanks, couple of minor suggestions here

2023-01-13 00:49 UTC, benfred commented on cpp/include/raft/spatial/knn/detail/ann_quantized.cuh
> +                      metric == raft::distance::DistanceType::L2SqrtUnexpanded ||
I've changed to use a switch statement like you suggested - .

Note that this check in ann_quantized is going to be deleted in the next week or so - I'm working on removing the faiss dependency from RAFT, and once https://github.com/rapidsai/raft/pull/1121 is merged we won't need this check anymore.

2023-01-13 00:50 UTC, benfred commented on cpp/include/raft/spatial/knn/detail/ivf_flat_search.cuh
> +  }
Good idea! 

I took a pass at adding a lambda argument to do post processing to queue.store in the last commit - can you take a look?

2023-01-13 07:34 UTC, achirkin approved these changes
Thanks, LGTM!

2023-01-13 07:34 UTC, achirkin commented on cpp/include/raft/spatial/knn/detail/topk/warpsort_topk.cuh
> +  __device__ void store(T* out, IdxT* out_idx, Lambda post_process = raft::identity_op()) const
Just for the record: I'm currently refactoring select_k in https://github.com/rapidsai/raft/pull/1085 , so I'd need to catch up with these changes there. I'm also planning to change `T` and `IdxT` into `OutT` and `OutIdxT` to allow saving the results in a type different from the working types `T` and `IdxT`.

2023-01-13 07:36 UTC, achirkin commented on cpp/include/raft/spatial/knn/detail/ann_quantized.cuh
> +                      metric == raft::distance::DistanceType::L2SqrtUnexpanded ||
Thanks, looking forward to #1121 !

2023-01-13 11:11 UTC, cjnolet approved these changes

2023-01-13 11:11 UTC, cjnolet commented
/merge

2023-01-13 17:26 UTC, benfred commented
/merge

2023-01-13 17:26 UTC, merged