Add gather & gatherv to raft::comms::comms_t
rapidsai/raft pull request #114
Opened 2020-12-10 21:18 UTC by seunghwak

- Add gather & gatherv to raft::comms::comms_t, raft::comms::std_comms_t, and raft::comms::mpi_comms_t

2020-12-10 21:20 UTC, seunghwak commented
This addresses #114

2020-12-11 16:47 UTC, cjnolet requested changes
The addition LGTM. Can you also expose a small test through `test.hpp`? Ideally we would also expose it to the Python layer for sanity checks.

2020-12-11 18:48 UTC, seunghwak commented
> The addition LGTM. Can you also expose a small test through `test.hpp`? Ideally we would also expose it to the Python layer for sanity checks.

Sure, I will. I will test this locally with cuGraph first, and then, I will add a test suite.

2021-02-03 15:17 UTC, seunghwak commented
rerun tests.

2021-02-03 16:36 UTC, afender approved these changes
Looks good to me

2021-02-03 17:37 UTC, cjnolet approved these changes
LGTM pending CI

2021-02-03 17:37 UTC, merged