add docs_build step
rapidsai/raft pull request #1168
Opened 2023-01-24 14:47 UTC by AyodeAwe

The PR adds a `docs_build` process to the PR and Build workflows for this repository. The generated docs are synced to s3 for only the build workflows.

2023-01-30 18:57 UTC, ajschmidt8 commented on dependencies.yaml
> +          - recommonmark
`breathe` is on this list twice.

also, the `pip` method of installing packages should be reserved for packages that aren't available on Anaconda.org.

It looks like all of these `pip` packages are currently available on Anaconda.org:

- https://anaconda.org/conda-forge/pydata-sphinx-theme
- https://anaconda.org/conda-forge/breathe
- https://anaconda.org/conda-forge/sphinx-copybutton
- https://anaconda.org/conda-forge/sphinx-markdown-tables

Therefore this `pip` section should be removed and its dependencies should be moved up a level.

2023-02-01 21:50 UTC, cjnolet commented
@AyodeAwe it looks like we got past the depenendencies issue but now there's an issue of it not finding the docs index (should *should* have been built during the C++ libraft).

2023-02-01 21:56 UTC, cjnolet requested changes

2023-02-01 21:56 UTC, cjnolet commented on ci/build_docs.sh
> +sphinx-build -b dirhtml source build -W
RAFT uses a plugin called `breathe` for sphinx, which means cmake also gets involved in the docs build process and the python docs build is combined w/ the c++ docs build. Is there any reason we can't use `./build.sh docs` here?

2023-02-03 20:47 UTC, cjnolet approved these changes
LGTM!

2023-02-03 21:19 UTC, ajschmidt8 requested changes
This PR will need a few changes.

Blocking the merge until I have time for a proper review.

2023-02-03 21:28 UTC, cjnolet commented
Sounds good @ajschmidt8 i was just very happy to see the docs seemed to build successfully in the logs.

2023-02-08 02:23 UTC, ajschmidt8 commented
To do:

- address these warnings: https://github.com/rapidsai/raft/actions/runs/4118640487/jobs/7112560748#step:6:721

2023-02-13 23:37 UTC, ajschmidt8 commented on .github/workflows/build.yaml
> +    uses: rapidsai/shared-action-workflows/.github/workflows/custom-job.yaml@cuda-118
```suggestion
    uses: rapidsai/shared-action-workflows/.github/workflows/custom-job.yaml@branch-23.04
```

2023-02-13 23:37 UTC, ajschmidt8 commented on .github/workflows/pr.yaml
> +    uses: rapidsai/shared-action-workflows/.github/workflows/custom-job.yaml@cuda-118
```suggestion
    uses: rapidsai/shared-action-workflows/.github/workflows/custom-job.yaml@branch-23.04
```

2023-02-17 18:28 UTC, ajschmidt8 approved these changes

2023-02-17 18:28 UTC, ajschmidt8 commented
/merge

2023-02-17 18:28 UTC, merged