[REVIEW] Make NCCL root initialization configurable.
rapidsai/raft pull request #120
Opened 2021-01-13 20:53 UTC by drobison00

This updates the raft comms implementation to support configurable NCCL root placement, updates scheduler and worker routine logging so that it is visible and usable in a multi-node deployment, and adds additional error handling to the NCCL initialization process to fail early if errors are encountered.

Updates resolve MNMG failures in out of band cuML algorithms where the DASK client does not have the ability to directly communicate with workers.

Unit tests are implemented and passing.

Closes https://github.com/rapidsai/cuml/issues/3261

2021-01-14 00:08 UTC, drobison00 commented
Rerun tests

2021-01-14 17:20 UTC, drobison00 commented
Tests currently failing in CI appear to be due to : https://github.com/rapidsai/ucx-py/issues/668

2021-01-14 17:54 UTC, cjnolet requested changes
Looks good overall. Just a few minor things to consolidate some of the logic and ease the maintenance burden a little bit.

2021-01-14 17:54 UTC, cjnolet commented on python/raft/dask/common/comms.py
> +        if nccl_root_location.lower() not in Comms.valid_nccl_placements:
Little nitpick- can we call `lower()` once? Maybe assign to `self` first and then raise the error if `self.nccl_root_location not in Comms.valid_nccl_placements`.

2021-01-14 17:54 UTC, cjnolet commented on python/raft/dask/common/comms.py
> +        if self.nccl_root_location == "client":
Can we pull this logic into a function like `create_nccl_uniqueid()`?

2021-01-14 17:54 UTC, cjnolet commented on python/raft/dask/common/comms.py
> +    if not hasattr(dask_scheduler, "_raft_comm_state"):
This function looks like it's pretty much a copy of `worker_state`. Could we consolidate these into a function that takes the scheduler/worker instance?

2021-01-14 17:54 UTC, cjnolet commented on python/raft/dask/common/comms.py
> +    )
Same with `_func_set_worker_as_nccl_root` and `_func_set_scheduler_as_nccl_root`, these look exactly the same with the only difference being the `get_worker` or `dask_scheduler`. I'm also okay just having these separate functions call a shared function like `_func_set_as_nccl_root(sessionId, process_instance, verbose)`

2021-01-14 17:54 UTC, cjnolet commented on python/raft/test/test_comms.py
> +    if not hasattr(dask_scheduler, "_raft_comm_state"):
Same here (with regards to consolidation)

2021-01-19 19:34 UTC, drobison00 commented
Rerun tests

2021-01-19 21:50 UTC, dantegd commented
rerun tests

2021-01-19 22:13 UTC, cjnolet approved these changes
LGTM

2021-01-19 22:29 UTC, dantegd commented
@drobison00 this is a breaking change, right? Then cugraph will also need a similar PR to https://github.com/rapidsai/cuml/pull/3386 to upgrade their tagged commit

cc @afender @BradReesWork for vis

2021-01-19 22:41 UTC, drobison00 commented
@dantegd added a PR to reflect the changes: https://github.com/rapidsai/cugraph/pull/1343

Once the raft update is merged, I can update git tags as well.

2021-01-20 17:40 UTC, merged