Fix compile time explosion for minkowski distance
rapidsai/raft pull request #1254
Opened 2023-02-07 14:24 UTC by ahendriksen

As explained in https://github.com/rapidsai/raft/issues/1246#issuecomment-1420828523, ptxas chokes on the minkowski distance when `VecLen==4` and `IdxT==uint32_t`.

This PR removes the veclen == 4 specialization for the minkowski distance.

2023-02-08 14:06 UTC, cjnolet requested changes
Not sure how I missed this one originally but I'd like to keep the (modern) naming conventions more consistent across the APIs. 

Also, I want to make sure the seemingly lower compile times aren't the result of sccache (which is suspect they are) and giving us false hope here. This is what happened before the release (we saw 45 minute compile times because of sccache, got excited, and then realized after the sccsche reset that the compile times were still taking >6 hours. I'd like to do some more profiling of this before merging.

2023-02-08 14:33 UTC, ahendriksen commented on cpp/include/raft/distance/masked_nn.cuh
> +void maskedL2NN(raft::device_resources const& handle,
Gladly!

2023-02-08 14:35 UTC, ahendriksen commented
> Also, I want to make sure the seemingly lower compile times aren't the result of sccache

Did you reset sccache in commit https://github.com/rapidsai/raft/pull/1254/commits/585fc47d2183823d2bd21377dda35c615d52f00f or do we still have to test this?

2023-02-08 14:37 UTC, cjnolet commented
I tried to but that didn't seem to work. I'm going to build locally without sccache in the meantime since my workstation specs are similar to CI.

2023-02-08 18:37 UTC, cjnolet approved these changes
I'm going ahead and approving this guy because I think the build issues related to these changes have been fixed. The other build issues predate these changes, I believe.

2023-02-09 00:05 UTC, cjnolet commented
/merge

2023-02-09 00:22 UTC, cjnolet commented
@ahendriksen just leaving a note for later that we should pull the `masked_l2_1nn_params` out from `masked_nn.cuh` and put it in a file called `mask_nn_types.hpp`. This allows users to expose that through their own APIs (knowing it doesn't require nvcc).

2023-02-09 01:24 UTC, sean-frye approved these changes
LGTM

2023-02-09 01:24 UTC, merged