Update and standardize IVF indexes API
rapidsai/raft pull request #1328
Opened 2023-03-10 10:59 UTC by viclafargue

Update and standardize IVF indexes API + edits on specializations

2023-03-10 15:36 UTC, achirkin requested changes
Thanks for the PR! Would you mind moving the 'xxx_params' to a second argument in all apis instead of the last one? That will be "much less breaking" change, because the initial implementation, both public and `detail`, followed this pattern.

2023-03-10 15:39 UTC, cjnolet requested changes
Thanks for fixing these changes. It's look good so far but want to make sure we are still being consistent with the other APIs in the codebase. 

For consistency, we use the following order of arguments always:

1. Handle 
2. Params structs
3. In 
4. Out 
5. Additional (non struct) parameters

2023-03-10 15:39 UTC, cjnolet commented on cpp/bench/neighbors/knn.cuh
> +    index.emplace(raft::neighbors::ivf_pq::build(
We don't want to revert this back to the pointer based APIs. We should always be preferring the mdspan APIs now (eventually pointer APIs will be removed)

2023-03-10 15:39 UTC, cjnolet commented on cpp/bench/neighbors/knn.cuh
> +      handle, search_params, *index, search_items, ps.n_queries, ps.k, out_idxs, out_dists);
Here too with using mdspan APIs.

2023-03-10 15:39 UTC, cjnolet commented on cpp/include/raft/neighbors/ivf_flat.cuh
> +            const search_params& params)
I would prefer that we keep any params structs to be the second argument (after the handle) and then any additional single parameter arguments come last. 

This is the way it's done across the codebase. Kmeans is a good example of an API outside of neighbors that uses that design.

2023-03-10 19:18 UTC, lowener commented on cpp/include/raft/neighbors/ivf_flat.cuh
> +template <typename value_t, typename idx_t>
Remove the `@tparam` documentation for this as well

2023-03-14 20:15 UTC, cjnolet requested changes
PR is looking good. I think just some updates to the docs of the arguments to consistently use `[in]`, `[out]` and `[inout]` everywhere.

2023-03-14 20:15 UTC, cjnolet commented on cpp/include/raft/neighbors/ivf_flat.cuh
> + * @param handle
handle should be `[in]`

2023-03-15 16:41 UTC, cjnolet commented on python/pylibraft/pylibraft/common/mdspan.pxd
> +cdef optional[device_matrix_view[int64_t, int64_t, row_major]] create_optional(
I don't know if cython will allow automatic overloads of this based on type, will it? We might need to rename this something like `make_optional_view_int64` or something.

2023-03-15 16:43 UTC, cjnolet approved these changes
This looks good to me so I'm approving. I think we should visit the `create_optional` overload in an immediate follow-on though. What do you think?

2023-03-15 17:07 UTC, achirkin approved these changes

2023-03-16 09:21 UTC, cjnolet commented
/merge

2023-03-16 09:37 UTC, merged