This PR adds support to __half and nb_bfloat16 to myAtomicReduce
rapidsai/raft pull request #1585
Opened 2023-06-09 10:50 UTC by Kh4ster

2023-06-09 12:02 UTC, Nyrio requested changes

2023-06-09 12:02 UTC, Nyrio commented on cpp/include/raft/util/cuda_utils.cuh
> +                "__half is only supported on __CUDA_ARCH__ >= 530");
CI is failing due to those static assertions. The assertions need to depend on a template parameter to fail only at the time of instantiation.

2023-06-09 16:04 UTC, Nyrio approved these changes

2023-06-10 03:37 UTC, cjnolet approved these changes

2023-06-10 03:38 UTC, cjnolet commented
/merge

2023-06-10 03:38 UTC, merged