Fix build.sh to enable NEIGHBORS_ANN_CAGRA_TEST
rapidsai/raft pull request #1724
Opened 2023-08-08 05:45 UTC by enp1s0

This PR update build.sh to enable NEIGHBORS_ANN_CAGRA_TEST.

2023-08-08 11:39 UTC, bdice approved these changes
CMake approval.

2023-08-08 11:41 UTC, bdice commented on build.sh
> +          $CMAKE_TARGET == *"NEIGHBORS_ANN_CAGRA_TEST" || \
Some of these lines look like this suggestion. Please verify the intended spelling. Looks like NEIGHBORS_TEST is an exception as well.
```suggestion
          $CMAKE_TARGET == *"NEIGHBORS_ANN_CAGRA_TEST"* || \
```

2023-08-08 11:41 UTC, bdice commented on build.sh
>            $CMAKE_TARGET == *"NEIGHBORS_TEST" || \
```suggestion
          $CMAKE_TARGET == *"NEIGHBORS_TEST"* || \
```

2023-08-08 11:42 UTC, bdice requested changes
Noticed a couple small things after approving, requesting changes for that.

2023-08-08 11:44 UTC, bdice commented on build.sh
> +TEST_TARGETS="CLUSTER_TEST;CORE_TEST;DISTANCE_TEST;LABEL_TEST;LINALG_TEST;MATRIX_TEST;RANDOM_TEST;SOLVERS_TEST;SPARSE_TEST;SPARSE_DIST_TEST;SPARSE_NEIGHBORS_TEST;NEIGHBORS_TEST;STATS_TEST;UTILS_TEST;
Alphabetize.
```suggestion
TEST_TARGETS="CLUSTER_TEST;CORE_TEST;DISTANCE_TEST;LABEL_TEST;LINALG_TEST;MATRIX_TEST;NEIGHBORS_TEST;NEIGHBORS_ANN_CAGRA_TEST;RANDOM_TEST;SOLVERS_TEST;SPARSE_TEST;SPARSE_DIST_TEST;SPARSE_NEIGHBORS_TEST;STATS_TEST;UTILS_TEST"
```

2023-08-08 11:45 UTC, bdice commented on build.sh
> +          $CMAKE_TARGET == *"NEIGHBORS_ANN_CAGRA_TEST" || \
Also should this list be alphabetized? It is pretty close, just a few exceptions to alphabetical order.

2023-08-09 00:39 UTC, enp1s0 commented
Thanks @bdice for reviewing the changes. I have fixed the issues.

2023-08-09 00:41 UTC, bdice approved these changes

2023-08-09 00:48 UTC, cjnolet approved these changes

2023-08-09 00:48 UTC, cjnolet commented
/merge

2023-08-10 02:34 UTC, merged