Fixing merge conflicts for raft-ann-gbench PR
rapidsai/raft pull request #1769
Opened 2023-08-24 18:44 UTC by cjnolet

This is just fixing merge conflicts for #1661 to continue making progress on new self-contained Python packaging.

2023-08-28 17:07 UTC, ajschmidt8 commented
This PR has been marked untrusted due to the changes outlined in https://github.com/rapidsai/raft/pull/1774.

It looks like the PR has unsigned commits.

You can rebase your branch to sign the unsigned commits to avoid having to use an `/ok to test` comment for every subsequent push.

The blog post below outlines how you can do this:

- https://duan.ca/2016/12/24/rebase-multiple-git-commits-with-signing/

2023-08-29 00:04 UTC, cjnolet commented
/ok to test

2023-08-29 07:01 UTC, achirkin requested changes
Looking forward to using our new emerging benchmarks!
A few small things missed when merging on top of #1661
e.g. `cpp/bench/ann/src/common/conf.cpp` and `cpp/bench/ann/src/common/conf.h` have been removed there.

2023-08-29 13:01 UTC, cjnolet commented on cpp/bench/ann/src/common/benchmark.cpp
> +  }
@divyegala do you mind addressing this one? I've addressed the rest of the feedback.

2023-08-29 13:02 UTC, cjnolet commented
/ok to test

2023-08-29 13:46 UTC, achirkin requested changes
A couple more merge artifacts/typos.

2023-08-29 13:46 UTC, achirkin commented on cpp/bench/ann/src/common/conf.hpp
> +      if (!filename.compare(filename.size() - 4, 24, "fbin")) {
a typo? (found in diff against 1661)

2023-08-29 13:46 UTC, achirkin commented on cpp/bench/ann/src/common/benchmark.cpp
> +                 const nlohman::json& index_conf) -> std::unique_ptr<raft::bench::ann::ANN<T>>
`const nlohman::json& index_conf` is an extra argument that wasn't added to #1661

2023-08-29 13:46 UTC, achirkin commented on cpp/bench/ann/src/common/benchmark.cpp
> +  return fun(algo, distance, dim, conf, dev_list, index_conf);
Same as above, remove `index_conf`

2023-08-29 14:22 UTC, achirkin commented on cpp/bench/ann/src/common/benchmark.cpp
> +  }
I think this has some room for thought. Maybe we undo the changes w.r.t. #1661 here, and add/discuss them as a follow-up PR?

2023-08-29 14:46 UTC, cjnolet commented on cpp/bench/ann/src/common/benchmark.cpp
> +  }
@divyegala @achirkin just to be completely clear- this only applies to the single executable code path, right?

2023-08-29 14:52 UTC, achirkin commented on cpp/bench/ann/src/common/benchmark.cpp
> +  }
Yes, `common/benchmark.cpp` is the `ANN_BENCH` main file.

2023-08-29 14:55 UTC, cjnolet commented on cpp/bench/ann/src/common/benchmark.cpp
> +  }
So this file doesn't apply to the other `<ALGO>_ANN_BENCH` executables? If this change doesn't at all affect the default operation of the benchmarks then I"m find pulling this change out. However, if this change is needed in order for the scripts to function properly w/ the default build options in a conda environment, then I'd prefer to keep the changes in and update them later when we figure out the most ideal path forward.

2023-08-29 15:01 UTC, achirkin commented on cpp/bench/ann/src/common/benchmark.cpp
> +  }
Yes, `benchmark.cpp` file is not used in `<ALGO>_ANN_BENCH` executables at all, so you're safe :)

2023-08-29 15:27 UTC, dantegd approved these changes
Just reviewed as well as tested the changes and things look great

2023-08-29 19:09 UTC, cjnolet commented
/ok to test

2023-08-29 19:17 UTC, achirkin requested changes

2023-08-29 19:17 UTC, achirkin commented on cpp/bench/ann/src/common/benchmark.cpp
> +                 const nlohman::json& index_conf) -> std::unique_ptr<raft::bench::ann::ANN<T>>
```suggestion
                 const std::vector<int>& dev_list) -> std::unique_ptr<raft::bench::ann::ANN<T>>
```

2023-08-29 19:17 UTC, achirkin commented on cpp/bench/ann/src/common/benchmark.cpp
> +  return fun(algo, distance, dim, conf, dev_list, index_conf);
```suggestion
  return fun(algo, distance, dim, conf, dev_list);
```

2023-08-29 19:17 UTC, achirkin commented on cpp/bench/ann/src/common/conf.hpp
> +      if (!filename.compare(filename.size() - 4, 24, "fbin")) {
```suggestion
      if (!filename.compare(filename.size() - 4, 4, "fbin")) {
```

2023-08-30 06:51 UTC, achirkin approved these changes
cpp/bench changes LGTM!

2023-08-30 12:33 UTC, cjnolet commented
/merge

2023-08-30 15:42 UTC, merged