Updating README
rapidsai/raft pull request #1836
Opened 2023-09-21 16:12 UTC by nwstephens

The installation instructions in the readme contains a bug. The Conda instructions should include a reference to the CUDA version. Also, the build from source instructions were out of sync with the docs, so I'm pointing the reader to the docs instead of including all of the instructions in the readme.

2023-09-21 16:24 UTC, bdice approved these changes

2023-09-21 16:24 UTC, bdice commented on README.md
>  - `libraft-headers` RAFT headers
```suggestion
- `libraft-headers` RAFT headers.
```

2023-09-21 16:24 UTC, bdice commented on README.md
> +- `libraft` (optional) shared library containing pre-compiled template instantiations and runtime API.
```suggestion
- `libraft` (optional) shared library containing pre-compiled template instantiations and runtime APIs.
```

2023-09-26 18:30 UTC, cjnolet requested changes
I think overall, I'd like to not remove the C++ usage instructions nor give the impression that RAFT is solely a Python library. I think we *should* mention that we have benchmarking packages and docker containers and then link out to the `raft_ann_benchmarks.md` file for more information about installing and using the docker containers. 

RAFT is a C++ library w/ Python bindings. Even if we expose a C API or Java API, RAFT is still going to be a C++ library at its core, just like the rest of the C++ libraries in RAPIDS. I think users should expect to see a very quick overview of the ways to use RAFT on the front page and then follow a link to more comprehensive guide. We just need to make sure it's up to date and you've outlined here a couple places where they weren't updated.

2023-09-26 18:30 UTC, cjnolet commented on README.md
>  - `raft-dask` (optional) enables deployment of multi-node multi-GPU algorithms that use RAFT `raft::comms` in Dask clusters.
We probably want to add `raft-ann-bench` and `raft-ann-bench-cpu` here as well, since those are conda/python packages that ship w/ raft.

2023-09-26 18:30 UTC, cjnolet commented on README.md
> -|-------------|---------------------|----------------------------------------------------------|----------------------------------------|
For the reasons outlined above, I'd prefer not to remove this from the docs. For cmake users, these are very important. 

I also think should keep the `Source` section below, and continue pointing the user to the build and install guide for more comprehensive instructions.

2023-10-27 17:23 UTC, nwstephens commented
Duplicate. Closing.

2023-10-27 17:23 UTC, closed without merging