Add `raft::stats::recall`
rapidsai/raft pull request #1860
Opened 2023-09-27 19:51 UTC by divyegala

This PR adds a primitive to compute recall score for Nearest Neighbor Algorithms

2023-10-02 16:23 UTC, cjnolet requested changes

2023-10-02 16:23 UTC, cjnolet commented on cpp/include/raft/stats/neighborhood_recall.cuh
> + * @brief Calculate Neighborhood Recall score on the host for indices, distances computed by any
New functions need usage examples.

2023-10-02 16:23 UTC, cjnolet commented on cpp/include/raft/stats/neighborhood_recall.cuh
> + *
Usage example

2023-10-04 01:44 UTC, divyegala commented on cpp/include/raft/stats/detail/neighborhood_recall.cuh
> +        DistanceValueType m     = std::max(std::abs(dist), std::abs(ref_dist));
Good point!

2023-10-06 13:32 UTC, lowener approved these changes
LGTM

2023-10-07 01:42 UTC, cjnolet approved these changes

2023-10-09 16:24 UTC, merged