Adjust Hellinger pairwise distance to vaoid NaNs
rapidsai/raft pull request #189
Opened 2021-03-30 21:54 UTC by lowener

This change will fix NaNs that arise in Hellinger pairwise distance when the input to sqrt is negative.
These kind of inputs can happen even when the inputs are normalized row-wise to 1 due to accumulation of rounding approximation.

2021-03-30 22:01 UTC, divyegala approved these changes
Pre-approving since it's a small requested change

2021-03-30 22:01 UTC, divyegala commented on cpp/include/raft/sparse/distance/l2_distance.cuh
> +        value_t rectifier = (1 - input) > 0;
This should be bool. Just combine this with next line?

2021-03-30 22:08 UTC, cjnolet commented
We should just run an L1 norm on the input here to guarantee it's positive.  (that's what UMAP does, which provides this with their API).

2021-03-30 22:10 UTC, cjnolet requested changes
These are supposed to be probabilities but we should just run an L1 normalization on the input here to guarantee it's positive. (that's what UMAP does, which provides this with their API).

2021-04-01 01:34 UTC, lowener commented
Even when the inputs are L1 normalized this can arise. Running `csr_row_normalize_l1` at the start of this function to enforce it doesn't solve these negative values in sqrt. These negative values are often negative epsilon that comes from either the first sqrt or the inner product.

A solution could be to run csr_row_normalize_l1 and keep this rectifier for negative epsilon, or to add an `abs` function call before sqrt.

2021-04-01 03:44 UTC, cjnolet commented
I looked at your failed Pytest asserion in cuml. It looks like Hellinger is running into a similar problem that other expanded metrics had been facing where the diagonal (which should be 0's) has a nan. This is likely because of the subtle numerical instabilities w/ expanded euclidean-based metrics (catastrophic cancellations). 

One thing we can do is zero out the diagonal of the resulting matrix using the `initializeDiagonalMatrix` primitive.

2021-04-01 14:48 UTC, cjnolet approved these changes
LGTM

2021-04-01 14:48 UTC, cjnolet commented
@gpucibot merge

2021-04-01 15:02 UTC, merged