Add distance metrics L1, L2 and cosine and their tests from cuML
rapidsai/raft pull request #201
Opened 2021-04-09 12:12 UTC by mdoijade

2021-04-09 12:12 UTC, GPUtester commented
Can one of the admins verify this patch?

2021-04-09 12:12 UTC, GPUtester commented
Can one of the admins verify this patch?

2021-04-09 12:13 UTC, mdoijade commented
@teju85 for review and labels.

2021-04-12 08:00 UTC, mdoijade commented
@JohnZed @dantegd  I suppose whitelisting this PR is required for tests to run?

2021-04-14 08:35 UTC, teju85 requested changes
a couple of minor nitpicks

2021-04-14 08:35 UTC, teju85 commented on cpp/include/raft/distance/distance.cuh
> +#endif
IIRC, this was added because there were issues with cutlass. Now that we have rid ourselves of it, it should be ok to remove this

2021-04-14 08:35 UTC, teju85 commented on cpp/include/raft/distance/distance.cuh
> +#endif
same as above. This can be removed now.

2021-04-14 09:01 UTC, teju85 approved these changes
Changes LGTM

2021-04-14 16:40 UTC, JohnZed commented
add to allowlist

2021-04-14 18:30 UTC, mdoijade commented
@teju85 can you rerun the tests? 
seems like some ci issue in git clone caused build failure.
Running command git clone -q https://github.com/dask/distributed.git /tmp/pip-req-build-esdzkjaw

23:42:27   fatal: error reading section header 'shallow-info'

https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci-v0.20/job/raft/job/prb/job/raft-gpu-test/CUDA=11.2,GPU_LABEL=gpu,OS=ubuntu18.04,PYTHON=3.8/13/console

2021-04-15 01:03 UTC, teju85 commented
rerun tests

2021-04-15 07:30 UTC, mdoijade commented
Thanks @teju85 for rerunning the tests, again the same error :( 
@dantegd any idea if this is known issue ? 
https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci-v0.20/job/raft/job/prb/job/raft-gpu-test/CUDA=11.2,GPU_LABEL=gpu,OS=ubuntu18.04,PYTHON=3.8/13/console

2021-04-16 14:35 UTC, teju85 commented
rerun tests.

2021-04-16 15:50 UTC, mdoijade commented
@divyegala can I get your review approval ?

2021-04-16 16:18 UTC, divyegala approved these changes
Not sure why it's still needing my approval. LGTM because @teju85 has approved

2021-04-18 09:02 UTC, mdoijade commented
@teju85 can we merge this now?

2021-04-18 09:36 UTC, teju85 commented
@gpucibot merge

2021-04-18 09:36 UTC, merged