Add raft-ann-bench script to generate synthetic dataset
rapidsai/raft pull request #2023
Opened 2023-11-23 15:43 UTC by tfeher

This PR adds a Python script to generate synthetic dataset.

2023-11-23 15:46 UTC, tfeher commented
```bash
python -m raft-ann-bench.generate_dataset --rows 1000000 --cols 128 --dtype float32 dataset/base.fbin

 # After the dataset is generated, you can create query and ground truth files

python -m raft-ann-bench.generate_groundtruth dataset/base.fbin --output=dataset --queries=random --n_queries=10000

```

2023-11-26 16:18 UTC, divyegala requested changes

2024-05-21 15:55 UTC, cjnolet commented
@tfeher this is still a really valuable feature to have. I'm going to push to 24.08, given the looming code freeze. Also cc @dantegd since you are refactoring the Python APIs.

2024-11-20 22:15 UTC, closed without merging

2024-11-20 22:15 UTC, cjnolet commented
benchmarking tool has been migrated over to cuvS. Closing.