Add public enum for select-k algorithm selection
rapidsai/raft pull request #2046
Opened 2023-12-07 00:49 UTC by benfred

Add an enum that controls which select-k algorithm is used. This takes the enum that was in the raft_internal and exposes in the public api.  This lets users pick which select algorithm they want to use directly

2023-12-07 19:23 UTC, benfred commented
By adding all of the remaining different select-k variants to the matrix::select_k instantiations, this increases the libraft.so binary size from 425MB to 429MB (cuda11 x86_64). I think this is probably acceptable, given the alternative would be much more complex - @cjnolet @tfeher what are your thoughts here?

2023-12-11 09:17 UTC, achirkin commented on cpp/include/raft/matrix/select_k_types.hpp
> +enum class SelectAlgo {
Would it make sense to explicitly specify the underlying type here? In case we add a new implementation later and that formally can change the type.

2023-12-11 09:21 UTC, achirkin commented on cpp/include/raft/matrix/select_k_types.hpp
> +    default: return os << "unknown enum value";
nitpick: while we're at this, maybe print the underlying value in case anyone ever needs this for debugging?

2024-01-06 19:27 UTC, cjnolet requested changes
Wow, it's crazy how big the diff got for such a small change to the API. 

The new enumeration uses its own vocabularu, which is not going to be immediately obvious to anyone outside of the RAFT development team so we should briefly summarize. 

Otherwise, it all looks great to me!

2024-01-06 19:27 UTC, cjnolet commented on cpp/include/raft/matrix/select_k.cuh
> + *   the selection algorithm to use
Can we expand the algorithms here a bit to give a brief summary of what they mean? I expect this API to be used mostly by power users, but I can't imagine even power users (outside of RAFT immediate developers) would be able to use these options without a brief description and summary of why each might be used. It's also a great opportunity to add the "see also" for the air-top-k paper.

2024-01-10 00:30 UTC, cjnolet approved these changes
LGTM. Thanks Ben!

2024-01-10 00:56 UTC, cjnolet commented
/merge

2024-01-10 03:09 UTC, merged