Update to CCCL 2.2.0.
rapidsai/raft pull request #2049
Opened 2023-12-07 03:55 UTC by bdice

This PR updates cuDF to CCCL 2.2.0. Do not merge until all of RAPIDS is ready to update.

Depends on https://github.com/rapidsai/rapids-cmake/pull/495.

Replaces #1464.

2023-12-18 15:32 UTC, bdice commented on ci/build_cpp.sh
> +LIBRMM_CHANNEL=$(rapids-get-pr-conda-artifact rmm 1404 cpp)
I will revert changes to CI scripts that use upstream artifacts before merging.

2023-12-18 15:33 UTC, bdice commented on fetch_rapids.cmake
> +set(rapids-cmake-branch cuco-cccl-2.2.0)
I will revert this before merging. Depends on https://github.com/NVIDIA/cuCollections/pull/404/ merging, and rapids-cmake being updated to use that commit in `versions.json`.

2023-12-18 20:02 UTC, vyasr requested changes

2023-12-18 20:02 UTC, vyasr commented on cpp/CMakeLists.txt
> +  include(cmake/thirdparty/get_cccl.cmake)
Is there a reason that raft can't use the CCCL in rmm? Can you check this? I'm guessing that the end result is equivalent right now, except that by calling this first we end up bundling CCCL into raft _in addition_ to rmm.

2023-12-18 21:52 UTC, vyasr commented on cpp/CMakeLists.txt
> +  include(cmake/thirdparty/get_cccl.cmake)
This diagnosis is correct, but we discussed offline and decided to live with this to allow easier testing of CCCL. The long-term fix will be to switch to a centralized package for CCCL dependencies that will remove the bundling concern in conda.

2023-12-18 21:52 UTC, vyasr approved these changes

2023-12-19 16:48 UTC, robertmaynard approved these changes

2023-12-19 16:49 UTC, bdice commented on cpp/CMakeLists.txt
> +  target_link_libraries(raft INTERFACE rmm::rmm cuco::cuco nvidia::cutlass::cutlass CCCL::Thrust)
```suggestion
  target_link_libraries(raft INTERFACE rmm::rmm cuco::cuco nvidia::cutlass::cutlass CCCL::CCCL)
```

2023-12-19 17:26 UTC, bdice commented
/merge

2023-12-19 20:48 UTC, merged

2023-12-20 13:49 UTC, dantegd commented
/merge