Benchmark brute force knn
rapidsai/raft pull request #2063
Opened 2023-12-13 20:47 UTC by benfred

Add our bfknn code to the raft-ann-bench project

2023-12-15 03:05 UTC, cjnolet requested changes
Looks good, I think it just needs a static assertion so we can throw an error if an unsupported data type is used.

2023-12-19 22:20 UTC, benfred commented
>Looks good, I think it just needs a static assertion so we can throw an error if an unsupported data type is used.

@cjnolet I added the static assert here https://github.com/rapidsai/raft/pull/2063/commits/f71f6578dd39a1e9885177bd186832aa8f54cdf7

2023-12-19 23:27 UTC, cjnolet approved these changes

2023-12-20 00:04 UTC, benfred commented
/merge

2023-12-20 00:04 UTC, merged