Only install compiled component in build_libraft.sh.
rapidsai/raft pull request #2209
Opened 2024-03-04 19:57 UTC by bdice

Proposal for closing #2175.

2024-03-04 19:59 UTC, bdice commented on conda/recipes/libraft/build_libraft.sh
> +cmake --install cpp/build --component compiled
This now looks a lot like https://github.com/rapidsai/raft/blob/branch-24.04/conda/recipes/libraft/build_libraft_static.sh except with a different component being installed.

2024-03-04 20:12 UTC, msarahan commented
compared with https://github.com/rapidsai/raft/pull/2208, this approach avoids the top-level build. I think this PR is probably a better approach. Certainly fewer changes, and it *should* have the same effect. I'd be happy to close #2208, but I'll let you guys have the say on whether you want to.

2024-03-04 22:49 UTC, bdice commented
This is failing for some reason due to `hnswlib`. I haven't had a chance to debug this yet. Just copying it here for awareness, for the moment.

```
CMake Error at /opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/cmake/raft/raft-targets.cmake:61 (set_target_properties):
  The link interface of target "raft::raft" contains:

    hnswlib::hnswlib

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/cmake/raft/raft-config.cmake:84 (include)
  build/cmake/CPM_0.38.5.cmake:243 (find_package)
  build/cmake/CPM_0.38.5.cmake:303 (cpm_find_package)
  build/_deps/rapids-cmake-src/rapids-cmake/cpm/find.cmake:189 (CPMFindPackage)
  cmake/thirdparty/get_raft.cmake:36 (rapids_cpm_find)
  cmake/thirdparty/get_raft.cmake:57 (find_and_configure_raft)
  CMakeLists.txt:34 (include)
```

2024-03-05 15:21 UTC, robertmaynard commented
> This is failing to build libraft-template for some reason due to hnswlib

The `libraft-template` builds build against an installed version of libraft. The installed version of libraft is now just installing the `libraft` target which means that the hnswlib headers / library aren't being installed into the `libraft` conda package. Which causes the consumers to fail.

The hnswlib install rules in `get_hnswlib.cmake` need to be expanded with an explicit `COMPONENT` and that component needs to get added to `cmake --install` invocation.

2024-03-05 22:50 UTC, bdice commented
@robertmaynard It looks like I got the same error again. https://github.com/rapidsai/raft/actions/runs/8159304257/job/22303364726?pr=2209#step:7:3758

Can you look at the implementation (c101777bbf47aaf1a1d815920c004cea1d2e1c95) and offer guidance?

2024-03-06 14:58 UTC, robertmaynard requested changes

2024-03-06 14:58 UTC, robertmaynard commented on cpp/cmake/thirdparty/get_hnswlib.cmake
>        install(DIRECTORY "${hnswlib_SOURCE_DIR}/hnswlib/" DESTINATION include/hnswlib)
You need to install the hnswlib headers as part of the `hnswlib` component

2024-03-06 17:04 UTC, robertmaynard commented on cpp/CMakeLists.txt
>    # CCCL before rmm/cuco so we get the right version of CCCL
I was thinking the issue was due to `rmm` encoding where to search for the RAPIDS version of CCCL, but that isn't the case. Reverting the change.

2024-03-06 18:01 UTC, robertmaynard approved these changes

2024-03-06 18:03 UTC, bdice commented
Thanks @robertmaynard for the help in debugging!

2024-03-06 18:28 UTC, bdice commented
It looks like `libraft-tests` is packaging `libraft.a` now. I suspect this is because it is no longer provided by the `libraft` conda package, but is still being built by the tests? Investigating now.

2024-03-06 22:57 UTC, bdice commented
@robertmaynard I couldn't figure out how to make the `build_libraft_tests.sh` _not_ build/install the static library, so instead I added `libraft-static` as a `host` dependency of `libraft-tests`. Hopefully this will keep it from repackaging the static library and other files. See baed39a23fa92910e8b3de7de6ab3b58ac6d5820.

If we can figure out how to make the tests avoid building the static library, that would be a better solution.

2024-03-07 03:34 UTC, bdice commented
As of baed39a, we are packaging the right things. It may be possible to cut down the build process further (by not building `libraft.a` for the `libraft-tests` package, or reusing other parts of the build for `libraft-tests`), but at least the resulting packages contain only the relevant pieces.

In total, this PR shrinks the binary size of the entire C++ conda channel by around 20%, from 1.5 GB to 1.2 GB. The main difference is dropping the extraneous copy of `libraft.a` that was in the `libraft` package.

2024-03-07 04:30 UTC, cjnolet approved these changes

2024-03-07 14:13 UTC, bdice commented
/merge

2024-03-07 14:20 UTC, raydouglass approved these changes

2024-03-07 14:20 UTC, merged