Batch cutlass distance kernels along N matrix dim
rapidsai/raft pull request #2215
Opened 2024-03-06 19:41 UTC by mdoijade

- batch input matrix with N-dim to at most 65535 to avoid cutlass gridY limitation.

2024-03-08 11:05 UTC, tfeher requested changes
Thanks Mahesh for fixing the issue! The PR looks good to me, but could you still add a test?

2024-03-08 11:33 UTC, mdoijade commented on cpp/include/raft/distance/detail/pairwise_distance_cutlass_base.cuh
> +  constexpr uint32_t gridYZMax      = ((1 << (sizeof(uint16_t) * 8)) - 1);
It is taken from cutlass code, this is how they decide limit. We can certainly replace it with `65535` if you are in favor for that.

2024-03-12 09:13 UTC, tfeher commented on cpp/include/raft/distance/detail/pairwise_distance_cutlass_base.cuh
> +  constexpr uint32_t gridYZMax      = ((1 << (sizeof(uint16_t) * 8)) - 1);
We can keep it to be consistent with cutlass.

2024-03-13 15:44 UTC, tfeher approved these changes
Thanks Mahesh for the update, LGTM!

2024-03-14 07:34 UTC, tfeher commented
/merge

2024-03-14 07:34 UTC, merged