Docstring and fix generate grountruth
rapidsai/raft pull request #2377
Opened 2024-07-11 07:48 UTC by Kh4L

Fix docstring and default `metric` as sqeuclidean is not supported in raft-ann-bench

2024-07-11 15:18 UTC, divyegala commented on python/raft-ann-bench/src/raft_ann_bench/generate_groundtruth/__main__.py
> +--queries=/dataset/query.public.10K.fbin /dataset/base.fbin
What has changed here? I think we would like to keep the --dataset argument

2024-07-14 21:00 UTC, tfeher requested changes
Thanks @Kh4L for this PR! In the PR description you write that "sqeuclidean is not supported in raft-ann-bench". I think that is not correct, I have tested in 24.06 and 24.08, and it is supported in both cases. Therefore I would recommend to keep the default metric "sqeuclidean". The rest of the docstring change look good to me.

2024-08-07 15:44 UTC, tfeher approved these changes
Thanks Serge, LGTM!

2024-11-20 22:15 UTC, cjnolet commented
Benchmarking tool has been migrated over to cuVS. Closing

2024-11-20 22:15 UTC, closed without merging