WIP: introduce libraft wheels
rapidsai/raft pull request #2531
Opened 2024-12-17 16:15 UTC by jameslamb

2024-12-17 17:56 UTC, jameslamb commented
/ok to test

2024-12-17 17:59 UTC, jameslamb commented
/ok to test

2024-12-17 18:19 UTC, jameslamb commented
/ok to test

2024-12-17 18:51 UTC, jameslamb commented
/ok to test

2024-12-17 19:12 UTC, jameslamb commented
/ok to test

2024-12-17 19:40 UTC, jameslamb commented
/ok to test

2024-12-17 20:17 UTC, jameslamb commented
/ok to test

2024-12-17 20:56 UTC, jameslamb commented
/ok to test

2024-12-17 21:21 UTC, jameslamb commented
/ok to test

2024-12-18 21:34 UTC, jameslamb commented
/ok to test

2024-12-24 18:22 UTC, jameslamb commented
/ok to test

2025-01-02 17:34 UTC, jameslamb commented
/ok to test

2025-01-06 19:14 UTC, jameslamb commented
/ok to test

2025-01-08 17:12 UTC, jameslamb commented
/ok to test

2025-01-09 01:01 UTC, jameslamb commented
/ok to test

2025-01-10 17:55 UTC, jameslamb commented
/ok to test

2025-01-13 14:08 UTC, jameslamb commented
/ok to test

2025-01-14 05:01 UTC, jameslamb commented
/ok to test

2025-01-14 20:13 UTC, bdice commented on python/raft-dask/raft_dask/common/CMakeLists.txt
>                                                                              CXX
Seems like this doesn't follow CMake style conventions with the `CXX` aligned so far to the right, after removing the `ASSOCIATED_TARGETS raft` piece. Do style checks not complain? Maybe check into that.

2025-01-14 20:13 UTC, bdice commented on python/raft-dask/raft_dask/include_test/CMakeLists.txt
>                                                                              CXX
Seems like this doesn't follow CMake style conventions with the `CXX` aligned so far to the right, after removing the `ASSOCIATED_TARGETS raft` piece. Do style checks not complain? Maybe check into that.

2025-01-14 21:56 UTC, bdice approved these changes

2025-01-15 00:50 UTC, vyasr requested changes
Generally looks good. Some things to look into briefly before we finalize. I would also cross-check with #2264 to make sure that nothing was missed here.

2025-01-15 00:50 UTC, vyasr commented on .github/workflows/pr.yaml
> +      # - devcontainer
TODO: Put this back before merging.

2025-01-15 00:50 UTC, vyasr commented on .github/workflows/pr.yaml
> +    needs: [checks, wheel-build-libraft]
I suppose this is an intentional increasing of the parallelism of the build? I think we decided we liked starting the build job without waiting for prior test jobs in other repos so this seems fine, just making sure that we're aligning.

2025-01-15 00:50 UTC, vyasr commented on ci/build_wheel_libraft.sh
> +export SKBUILD_CMAKE_ARGS="-DDETECT_CONDA_ENV=OFF${EXTRA_CMAKE_ARGS}"
Honestly I don't think we need to be setting this explicitly almost ever. All our wheel builds occur in environments where we don't have a conda environment. I'd prefer to remove this altogether.

If we did keep it though, minor nit: I would prefer to have an explicit semicolon here rather than embedding it in each incantation of `EXTRA_CMAKE_ARGS` above.
```suggestion
export SKBUILD_CMAKE_ARGS="${EXTRA_CMAKE_ARGS}"
```

2025-01-15 00:50 UTC, vyasr commented on .github/workflows/build.yaml
> +    needs: wheel-publish-libraft
The job downloads from s3, so really this can happen after the libraft build is complete and doesn't have to wait for publish, right?

2025-01-15 00:50 UTC, vyasr commented on ci/build_wheel_pylibraft.sh
> +export SKBUILD_CMAKE_ARGS="-DDETECT_CONDA_ENV=OFF"
As above, I think this is safe to remove.

2025-01-15 00:50 UTC, vyasr commented on ci/validate_wheel.sh
So basically we're fine skipping checks on raft-dask and pylibraft now that we know they're small, yeah?

2025-01-15 00:50 UTC, vyasr commented on cpp/CMakeLists.txt
> +option(RAFT_COMPILE_DYNAMIC_ONLY "Only build the shared library and skip the
I think that this is fine for now, but we should standardize our CMake strategies here a bit. raft is not the only RAPIDS library that people sometimes want static and at other times shared. I haven't fully thought through the ramifications of supporting both builds at once vs simply switching on `BUILD_SHARED_LIBS` (which is what cudf does IIRC). It gets extra confusing to think about the exports and whether you really need to build these as two separate packages or not. 

I don't want to block this PR on this though. Maybe open a build-planning issue for it (or remind me to do so tomorrow if you aren't sure what it should look like).

2025-01-15 00:50 UTC, vyasr commented on python/libraft/CMakeLists.txt
> +endif()
Why do we need this here? Does the C++ CMakeLists.txt not handle finding CUDA appropriately? I guess it's doing some extra error handling though which is handy. Maybe this is temporary until we drop CUDA 11 and we can use CUDA math wheels for all supported CUDA versions (at which point we won't need to find the CTK in this file anymore)?

2025-01-15 15:25 UTC, jameslamb commented on ci/build_wheel_libraft.sh
> +export SKBUILD_CMAKE_ARGS="-DDETECT_CONDA_ENV=OFF${EXTRA_CMAKE_ARGS}"
Ok that's fine, I can try removing it. Both of those patterns (setting `-DDETECT_CONDA_ENV` and the placement of the semicolon) are used all over RAPIDS wheel-building CI scripts (not newly introduced in this PR), so if that works here and we likes it I'll make other PRs across RAPIDS changing that.

2025-01-15 15:28 UTC, jameslamb commented on ci/validate_wheel.sh
No, they're still getting checked (see the invocations of `validate_wheel.sh` in their `ci/build_wheel_{project.sh}` scripts... and should be, to ensure they stay small.

They just don't need different thresholds by CUDA version any more. The explicit `--max-allow-size` for those packages getting removed here corresponds with the other changes where this is added to the `[tool.pydistcheck]` table in their `pyproject.toml`:

```toml
# PyPI limit is 100 MiB, fail CI before we get too close to that
max_allowed_size_compressed = '75M'
```

2025-01-15 15:46 UTC, jameslamb commented on python/libraft/CMakeLists.txt
> +endif()
> *Why do we need this here?*

This is here to set a value for `CUDA_STATIC_MATH_LIBRARIES`, which is closely related to the wheel-specific `USE_CUDA_MATH_WHEELS` (which controls whether or not to add RPATH entries looking for e.g. `libcublas.so` installed to `site-packages` via `nvidia-cublas-cu12`).

That isn't being newly introduced in this PR, it's just in the diff because it's being moved around. Here's where that was introduced:

* https://github.com/rapidsai/raft/pull/2376
* https://github.com/rapidsai/raft/pull/2415

> *Maybe this is temporary until we drop CUDA 11 and we can use CUDA math wheels for all supported CUDA versions (at which point we won't need to find the CTK in this file anymore)*

Yes, this.

2025-01-15 15:51 UTC, jameslamb commented on .github/workflows/build.yaml
> +    needs: wheel-publish-libraft
Yes, good point!!!

I'll change that here, and put up PRs across RAPIDS with changes like that.

Across RAPIDS, we have `wheel-build-*` depending on `wheel-publish-*` of its dependencies.

https://github.com/rapidsai/cudf/blob/e272f1e60978801809945c59240dfb02f0aa3b07/.github/workflows/build.yaml#L92-L93

https://github.com/rapidsai/cugraph/blob/6b5db94d9b6ebee41577222d230a36675d3e3ff4/.github/workflows/build.yaml#L90-L91

That extra parallelism should reduce the end-to-end time for publishing nightlies 😁

2025-01-15 17:06 UTC, jameslamb commented on python/raft-dask/raft_dask/common/CMakeLists.txt
>                                                                              CXX
Style checks don't complain, but looks like that's because they're not providing a config file for `cmake-format` / `cmake-lint`, making them no-ops:

https://github.com/rapidsai/raft/blob/a7f191639575f5bfcccf48d670ed33a34860f763/cpp/scripts/run-cmake-format.sh#L59-L65

Running those with the `rapids-cmake` config for those tools, I saw `cmake-format` make exactly the change you're talking about (pulling that `CXX` up onto the same line.

Pushed a commit doing that: https://github.com/rapidsai/raft/pull/2531/commits/a800691fffb61d9ed30280343d9ace26f8980cac

Copying what cudf does: https://github.com/rapidsai/cudf/blob/89e87036a310ed699214a427aefb79ba2ab050c1/ci/check_style.sh#L19-L24

The changes look small and non-controversial enough that I think it'd be fine to just include that in the scope of this PR. But happy to split it out if you disagree.

2025-01-15 17:12 UTC, jameslamb commented
😭 one of the earlier commits on this is unverified, so I'm gonna have to trigger CI with comments. Sorry for the notification noise, idk what happened there.

<img width="808" alt="Screenshot 2025-01-15 at 11 11 08 AM" src="https://github.com/user-attachments/assets/30bf74a6-d796-4334-a34c-ee5a2eac308d" />

2025-01-15 17:16 UTC, jameslamb commented on ci/build_wheel_libraft.sh
> +export SKBUILD_CMAKE_ARGS="-DDETECT_CONDA_ENV=OFF${EXTRA_CMAKE_ARGS}"
Removing it worked for me locally. Did that in https://github.com/rapidsai/raft/pull/2531/commits/1d9e1e97b594c2c84e175f37ab967bb853692255#diff-bf2a37f5233778a838d488772273c05401ae172253b19533bc07e7ca958ba271.

2025-01-15 17:16 UTC, jameslamb commented on ci/build_wheel_pylibraft.sh
> +export SKBUILD_CMAKE_ARGS="-DDETECT_CONDA_ENV=OFF"
addressed in https://github.com/rapidsai/raft/pull/2531#discussion_r1917056351

2025-01-15 17:17 UTC, jameslamb commented on dependencies.yaml
> +              - libraft-cu12==25.2.*,>=0.0.0a0
Fixed this in https://github.com/rapidsai/raft/pull/2531#discussion_r1917056351

Also checked that that caught everything like this:

```shell
./ci/release/update-version.sh '25.04.00'
git grep -E '25\.2'
git grep -E '25\.02\
git grep -E '24\.'
```

2025-01-16 15:23 UTC, jameslamb commented on cpp/CMakeLists.txt
> +option(RAFT_COMPILE_DYNAMIC_ONLY "Only build the shared library and skip the
Yeah thank you, I agree we shouldn't block this PR on this. I'd appreciate if you could open the issue, sounds like you have a more specific set of ideas about this than what I'd probably write.

2025-01-16 16:10 UTC, bdice approved these changes

2025-01-16 16:10 UTC, bdice commented
Approved additional changes since my last review.

2025-01-16 17:31 UTC, vyasr commented on ci/build_wheel_libraft.sh
> +export SKBUILD_CMAKE_ARGS="-DDETECT_CONDA_ENV=OFF${EXTRA_CMAKE_ARGS}"
Cool thanks. I'll defer to you on when and how you want to propagate these changes through the rest of RAPIDS.

2025-01-16 17:31 UTC, vyasr commented on .github/workflows/build.yaml
> +    needs: wheel-publish-libraft
Nice thanks! I'll let you handle doing this elsewhere as time permits.

2025-01-16 17:32 UTC, vyasr commented on ci/validate_wheel.sh
Ah got it OK that makes sense, thanks.

2025-01-16 17:32 UTC, vyasr commented on python/libraft/CMakeLists.txt
> +endif()
OK cool then that's fine.

2025-01-16 17:42 UTC, vyasr commented on cpp/CMakeLists.txt
> +option(RAFT_COMPILE_DYNAMIC_ONLY "Only build the shared library and skip the
I opened https://github.com/rapidsai/build-planning/issues/134.

2025-01-16 17:43 UTC, vyasr approved these changes
I left a couple of threads unresolved that require some follow-up work from you, but otherwise this PR LGTM now pending the devcontainer updates.

2025-01-16 17:51 UTC, jameslamb commented on .github/workflows/build.yaml
> +    needs: wheel-publish-libraft
No prob, no prob. I'm gonna wait until we've finished https://github.com/rapidsai/cugraph/pull/4804, in case that uncovers other this-should-change-across-all-of-RAPIDS things, then do a sweep of 1 PR per repo with these changes where necessary.

I'm keeping a list, so far I have:

* nightly / branch builds depending on `*-build` not `*-publish`
* PR builds depending on `*-build` not `*-tests`
* removing `-DDETECT_CONDA_ENV=OFF` from wheel-building scripts
* enforcing `rapids-cmake`'s preferred CMake formatting (https://github.com/rapidsai/raft/pull/2531#discussion_r1917039870)

2025-01-16 18:15 UTC, jameslamb commented
/ok to test

2025-01-16 18:17 UTC, jameslamb commented on .github/workflows/pr.yaml
> +      # - devcontainer
Just pushed https://github.com/rapidsai/raft/pull/2531/commits/93f39fb70031bdbd1e2a865692e2baf1089e225a restoring the devcontainer builds.

They'll still fail because the manifest in devcontainers needs to be updated. Summarizing plan we agreed to offline:

1. get devcontainers PR passing CI, pointed at this branch from my fork (https://github.com/rapidsai/devcontainers/pull/438)
2. admin-merge this PR
3. point that devcontainers PR back at `rapidsai/raft`, observe it passing CI, merge it normally

2025-01-16 22:34 UTC, divyegala approved these changes

2025-01-16 22:34 UTC, benfred approved these changes
lgtm!

2025-01-16 23:15 UTC, merged

2025-01-21 21:33 UTC, jameslamb commented on ci/build_wheel_libraft.sh
> +export SKBUILD_CMAKE_ARGS="-DDETECT_CONDA_ENV=OFF${EXTRA_CMAKE_ARGS}"
> when and how you want to propagate these changes through the rest of RAPIDS

Put up this tracking issue: https://github.com/rapidsai/build-planning/issues/136

I'm going to try to do that in the next day or 2, to try to get it into 25.02.