Add chebyshev, canberra, minkowksi and hellinger distance metrics
rapidsai/raft pull request #276
Opened 2021-06-15 15:19 UTC by mdoijade

2021-06-15 16:42 UTC, mdoijade commented
@teju85 @cjnolet  please help with review.

2021-06-15 17:27 UTC, cjnolet requested changes
Looks great. Just very minor things.

2021-06-16 14:09 UTC, mdoijade commented on cpp/include/raft/distance/chebyshev.cuh
> + * @tparam OutType output data-type (for C and D matrices)
done.

2021-06-16 14:09 UTC, mdoijade commented on cpp/include/raft/distance/chebyshev.cuh
> + * Copyright (c) 2018-2021, NVIDIA CORPORATION.
done.

2021-06-23 16:57 UTC, mdoijade commented
@cjnolet @teju85 the cuML side PR is passing - https://github.com/rapidsai/cuml/pull/3990
the failure in those tests is in dbscan due to some recent numpy update. 
All tests pertaining to these distance metrics are passing.

2021-06-24 20:45 UTC, cjnolet commented
@mdoijade, the dbscan / numpy issue should be fixed in this PR: https://github.com/rapidsai/cuml/pull/4012. 

Would it reduce the compile time at all if we just used function arguments for the individual distances and removed the explicit templates for them?

2021-06-24 20:52 UTC, cjnolet approved these changes
LGTM

2021-06-24 21:01 UTC, dantegd requested changes
Before we merge this PR, could you quantify the impact of the changes in cuML's compilation time (locally at least)?

2021-06-25 16:31 UTC, mdoijade commented
> 
> 
> Before we merge this PR, could you quantify the impact of the changes in cuML's compilation time (locally at least)?

@dantegd 
Without new distance metrics cuML total build time
real    9m24.016s
user    118m8.600s
sys     3m43.230s

With these 4 additional distance metrics cuML total build time
real    18m11.113s
user    120m28.920s
sys     3m34.880s

It is roughly 2x build time increase, and this reduction is after my change of using compiled cuML pairwise dist kernels instead of each time calling raft API wherever it is feasible without that change build time is about 25mins.
This increase is coming from pairwise_distance.cu

2021-06-29 13:34 UTC, mdoijade commented
@dantegd @cjnolet @teju85 
I split the `pairwise_distance.cu` compilation into multiple source files for each distance metric to enable parallel build in it,
this has helped by a certain extent from previous effort like around 2-3 mins build time reduction.
I am seeing that minkowksi kernels are taking longer than others with CUDA 11.0 it has "powf(), pow()"  functions in it that is the only difference.
so after disabling minkowski kernels (other 3 new kernels enabled) the time take for full cuML build with CUDA 11.0
real    9m35.232s
user    113m56.715s
sys     3m44.966s
this is almost same time as without these kernels.

With these 4 additional distance metrics cuML total build time without splitting - CUDA 11.0 
real 18m11.113s
user 120m28.920s
sys 3m34.880s

Without new distance metrics cuML build time - CUDA 11.0 (current baseline)
real    9m24.016s
user    118m8.600s
sys     3m43.230s


After splitting the distance prims in `pairwise_distance.cu` into individual source files (with minkowski) - CUDA 11.0
real    17m44.648s
user    127m42.492s
sys     3m48.588s

Without minkowski  - CUDA 11.0
real    9m35.232s
user    113m56.715s
sys     3m44.966s


With minkowski  - cuda 11.2 + split pairwise distance 
real    9m57.291s
user    123m47.790s
sys     3m54.819s

With minkowski  - cuda 11.2 + without split pairwise distance 
real    12m22.500s
user    118m22.608s
sys     3m45.721s

So it is evident that this splitting of `pairwise_distance.cu` does help reduce build time.
and there is some compilation slowness issue with cuda 11.0 for `pow(), powf()` which seems to be resolved in cuda 11.2.

2021-07-05 12:56 UTC, mdoijade commented
@dantegd can we merge this now? and also cuML PR - https://github.com/rapidsai/cuml/pull/3990

2021-07-06 13:09 UTC, dantegd approved these changes

2021-07-06 13:09 UTC, dantegd commented
@gpucibot merge

2021-07-06 13:09 UTC, merged