[REVIEW] Fix wrong lda parameter in gemv
rapidsai/raft pull request #327
Opened 2021-09-14 09:02 UTC by achirkin

Fix wrong lda parameter in raft::linalg::gemv. I also took a liberty to add couple more overloads and documentation.

2021-09-15 22:02 UTC, cjnolet requested changes
The changes and tests look great. Just one minor detail in the tests

2021-09-16 06:30 UTC, achirkin commented on cpp/test/linalg/gemv.cu
> +    CUDA_CHECK(cudaMalloc(&A, aElems * sizeof(T)));
Thanks Corey! Sure, can do.

2021-09-16 14:52 UTC, cjnolet approved these changes
LGTM. Thanks @achirkin!

2021-09-16 16:07 UTC, BradReesWork approved these changes

2021-09-16 16:09 UTC, ChuckHastings approved these changes

2021-09-16 17:39 UTC, cjnolet commented
@gpucibot merge

2021-09-16 17:39 UTC, merged