Use 64 bit CuSolver API for Eigen decomposition
rapidsai/raft pull request #349
Opened 2021-10-01 14:48 UTC by lowener

This PR replace the legacy call to `cusolverDnsyevj` with the 64-bit version.
It also improves the indexing types used, from int to size_t when possible.

2021-10-01 14:58 UTC, lowener commented
I just noticed that `DnXsyevd` was introduced in CUDA 11.1.0 in Sept. 2020. So the CI with CUDA version 11.0 will always fail.

2021-10-04 17:02 UTC, cjnolet commented
@lowener, 

> I just noticed that DnXsyevd was introduced in CUDA 11.1.0 in Sept. 2020. So the CI with CUDA version 11.0 will always fail.

Indeed, I remember discussing this very detail w/ @teju85 not too long ago. A good workaround here could be to be check the CUDA version and have the wrapper call the old version in 11.1.

2021-10-18 19:14 UTC, cjnolet requested changes

2021-11-05 17:35 UTC, cjnolet commented
@gpucibot merge

2021-11-05 17:35 UTC, merged