Hiding implementation details for random, stats, and matrix
rapidsai/raft pull request #356
Opened 2021-10-06 17:16 UTC by divyegala

2021-10-06 18:09 UTC, cjnolet requested changes
Looks like a great start. We want to make sure any classes which are being used internally and contain kernel-specific things are also being hidden behind detail and exposed through a proxy in the public API.

2021-10-06 18:09 UTC, cjnolet commented on cpp/include/raft/random/rng.cuh
>    void fill(Type *ptr, LenType len, Type val, cudaStream_t stream) {
It looks like there's quite abit of implementation details for the `Rng` type, including CUDA details. Also, if the hidden impls of the random generator kernels need access to the `Rng` class then the details API is going to be including this file and vice versa. One thing we can do is rename this to something like `RngImpl` and move it to `detail` and then expose it to the public API under the `Rng` name.

2021-10-06 18:09 UTC, cjnolet commented on cpp/include/raft/stats/mean.cuh
> +    detail::meanKernelRowMajor<Type, IdxType, TPB, ColsPerBlk>
Same here wrt invoking kernels from public API. Just proxy to the function in the details API.

2021-10-21 20:52 UTC, cjnolet approved these changes
Changes look great!

2021-10-21 20:52 UTC, cjnolet commented on cpp/include/raft/matrix/math.hpp
> +  detail::argmax(in, n_rows, n_cols, out, stream);
much better!

2021-11-09 04:16 UTC, dantegd requested changes

2021-11-09 04:16 UTC, dantegd commented on cpp/include/raft/random/rng.hpp
> +/*
cugraph uses rng.cuh in a couple of places, so leaving a quick review so we don’t merge this before that side is ready (if it already is, just let me know and glad to approve/merge)

2021-11-11 20:29 UTC, dantegd approved these changes

2021-11-11 20:30 UTC, dantegd commented
@gpucibot merge

2021-11-11 20:30 UTC, merged