single-pass raft::stats::meanvar
rapidsai/raft pull request #472
Opened 2022-02-01 14:37 UTC by achirkin

Add a helper to compute column-wise mean and variance for a matrix in a single pass.

Implementation and tests are to a large extent copy-pasted from `raft::stats::mean` and `raft::stats::stddev`.
It is to be used in cuml's `ML::GLM::preProcessData`, where it finishes ~1.8 faster compared to running mean+var separately (on column-major data).

2022-02-02 14:59 UTC, cjnolet requested changes
Looks great, just one very minor thing

2022-02-02 14:59 UTC, cjnolet commented on cpp/include/raft/stats/meanvar.hpp
> + * The operation is performed in a single sweep.
To help users who may not immediately see the benefit, can you briefly mention the performance implication / expected speedup of fusing these two operations in a single kernel?

2022-02-03 21:33 UTC, cjnolet approved these changes
LGTM

2022-02-04 06:16 UTC, achirkin commented
rerun tests

2022-02-04 19:31 UTC, cjnolet commented
rerun tests

2022-02-04 22:07 UTC, cjnolet commented
@gpucibot merge

2022-02-04 22:07 UTC, merged