Adding instructions to install from conda and build using CPM
rapidsai/raft pull request #519
Opened 2022-02-19 21:05 UTC by cjnolet

2022-02-19 22:04 UTC, cjnolet commented
Adding a quick note to self on the updated example for the new API:

```c++
```c++
#include <raft/handle.hpp>
#include <raft/distance/distance.hpp>
#include <raft/random/make_blobs.hpp>

raft::handle_t handle;

int n_samples = 5000;
int n_features = 50;

auto input = make_matrix(n_samples, n_features);
auto output = make_matrix(n_samples, n_samples);

int n_centers = 5;
raft::random::make_blobs(handle, input, n_centers);

auto metric = raft::distance::DistanceType::L2SqrtExpanded;
raft::distance::pairwise_distance(handle, input, input, output, metric);
```

2022-02-22 17:14 UTC, dantegd requested changes
Overall great additions to the documentation

2022-02-22 22:28 UTC, dantegd approved these changes

2022-02-22 22:34 UTC, cjnolet commented
@gpucibot merge

2022-02-22 22:34 UTC, merged