mdspan PoC for distance make_blobs
rapidsai/raft pull request #538
Opened 2022-03-01 21:42 UTC by cjnolet

2022-03-03 05:07 UTC, cjnolet commented
rerun tests

2022-03-07 22:37 UTC, dantegd requested changes
The changes look fantastic, just added comments about additional documentation

2022-03-07 22:37 UTC, dantegd commented on README.md
> -### Rapids Memory Manager (RMM)
RMM is still used and required, no? I think a less prominent mention somewhere might still be good to have. Additionally, I think a quick summary of mdspan/array/etc. might be good to have for newcomers.

2022-03-07 22:37 UTC, dantegd commented on README.md
> +The example below demonstrates creating a RAFT handle and using it with `device_matrix` and `device_vector` to allocate memory, generating random clusters, and computing
Another documentation that would be good to have is the fact that both old and new API are present but the new one is the way to go (and old one eventually will be deprecated).

2022-03-07 22:37 UTC, dantegd commented on README.md
> +The example below demonstrates creating a RAFT handle and using it with `device_matrix` and `device_vector` to allocate memory, generating random clusters, and computing
Another documentation that would be good to have is the fact that both old and new API are present but the new one is the way to go (and old one eventually will be deprecated).

2022-03-09 23:40 UTC, dantegd approved these changes

2022-03-09 23:40 UTC, cjnolet commented
@gpucibot merge

2022-03-09 23:40 UTC, merged