Improve performance of select-top-k  WARP_SORT implementation
rapidsai/raft pull request #606
Opened 2022-04-01 12:20 UTC by achirkin

A few simplifications and tricks to improve the performance of the kernel:

- Promote some constants to static constexpr
- Allow `capacity < WarpSize`
- Reduce the frequency of `sort` operations for `filtered` version

2022-04-06 09:31 UTC, achirkin commented
NB from previous discussions: I considered merging `done()` and `store(..)` together, but decided against that for two reasons:

  1. Atm, `store(...)` is rather fast and can be used to store the content multiple times, after `done()` has been called once. Looks like a useful behavior.
  2. I couldn't come up with a clean solution without the use of virtual functions, but I'm afraid introducing one would incur extra overheads.

2022-04-14 07:29 UTC, achirkin commented
NB: more tests are coming in https://github.com/rapidsai/raft/pull/618

2022-05-13 16:00 UTC, tfeher requested changes
Hi Artem, thanks for the PR! It looks good, just a found a few small things. 

Question, is the following statement true?  With these modifications, capacity < warpsize is allowed. Since the capacity is chosen automatically according to the k value, the existing test cover these changes.

Please add to the PR description that the warp_sort::load functions are removed to simplify the API.

2022-05-16 14:18 UTC, achirkin commented on cpp/include/raft/spatial/knn/detail/topk/warpsort_topk.cuh
> +   *    it's needed to make sure threads within warp don't diverge when kWarpWidth < WarpSize.
I'm referring there to `topk::bitonic(..).merge()`, which should run by all threads in a warp. In the code there, always only one of the following two is true: either `kWarpWidth < WarpSize` or the value of `do_merge` is the same for all threads in a warp.
Thanks for noting this, I'll update the documentation!

2022-05-16 15:47 UTC, tfeher approved these changes
Thanks Artem for addressing the issues! The PR looks good to me.

2022-05-16 16:11 UTC, cjnolet commented
@gpucibot merge

2022-05-16 16:11 UTC, merged