Revert print vector changes because of std::vector<bool>
rapidsai/raft pull request #681
Opened 2022-05-25 15:57 UTC by lowener

The specialization of `std::vector` when `T=bool` is unfortunately causing compilation issue in cuml because the `data()` function member is not implemented. And the elements may not be stored contiguously.

cc @achirkin

2022-05-25 16:02 UTC, cjnolet submitted a review, later dismissed
LGTM

2022-05-25 17:13 UTC, achirkin requested changes
Huh, good point :) still, let us not have manual allocations

2022-05-25 17:13 UTC, achirkin commented on cpp/include/raft/core/cudart_utils.hpp
> +  T* host_mem = new T[componentsCount];
Then, let it be a `unique_ptr` to avoid a memory leak on exception, e.g.
```
auto host_mem = std::make_unique<T[]>(componentsCount);
```

2022-05-26 01:07 UTC, cjnolet commented
I’m going to go ahead and merge this guy for now to fix the cuml build, though @lowener it would be nice if we could still address @achirkin’s concerns in a follow on PR (maybe for 22.08)

2022-05-26 01:08 UTC, cjnolet commented
@gpucibot merge

2022-05-26 01:08 UTC, merged