Support 32bit and unsigned indices in bruteforce KNN
rapidsai/raft pull request #730
Opened 2022-07-01 09:52 UTC by achirkin

Make KNN compilable with `IdxT == uint32_t` and add some benchmarks.

2022-07-01 09:55 UTC, achirkin commented
NB: this PR is required before merging #652, which expands on the benchmarks introduced here (trying to reduce the size of #652).

2022-07-01 12:13 UTC, robertmaynard approved these changes
CMake changes LGTM

2022-07-04 05:25 UTC, achirkin commented
rerun tests

2022-07-04 11:04 UTC, tfeher requested changes
Hi @achirkin, thanks for the RP, it looks good, just a small thing.

2022-07-04 11:07 UTC, achirkin commented on cpp/include/raft/spatial/knn/detail/haversine_distance.cuh
> +           std::numeric_limits<value_idx>::max(),
Yes. Otherwise, it's just a compiler warning about the narrowing conversion, which is the error in our setup.

2022-07-04 12:28 UTC, tfeher approved these changes
Thanks Artem for addressing the issue, the PR looks good to me.

2022-07-05 17:40 UTC, cjnolet commented
@gpucibot merge

2022-07-05 17:40 UTC, merged