[WIP] atomics: Add warp-aggregated atomic increment
rapidsai/raft pull request #735
Opened 2022-07-08 14:57 UTC by ahendriksen

Implement fast atomic counter increment using warp-aggregated atomics. Useful
for filtering.

Adapted from:
https://developer.nvidia.com/blog/cuda-pro-tip-optimized-filtering-warp-aggregated-atomics/

2022-07-08 15:00 UTC, ahendriksen commented
Moving this functionality from cuml to raft as discussed in https://github.com/rapidsai/cuml/pull/4803

2022-07-12 07:37 UTC, tfeher requested changes
Looks good. Please add a unit test.

2022-07-13 09:56 UTC, ahendriksen commented
I have added a unit test.

2022-07-13 17:48 UTC, tfeher approved these changes
Thanks @ahendriksen for adding the test! The PR looks good to me.

2022-07-14 20:11 UTC, cjnolet approved these changes
LGTM. Just a tiny question / nitpick in the test. Thanks @ahendriksen!

2022-07-14 20:11 UTC, cjnolet commented on cpp/test/device_atomics.cu
> +  RAFT_CUDA_TRY(cudaMemcpy(out_host.data(),
Can we use `raft::copy` here?

2022-07-14 20:11 UTC, cjnolet commented
@gpucibot merge

2022-07-14 20:11 UTC, merged