[WIP] - Gpuciscripts clean and update
rapidsai/raft pull request #92
Opened 2020-11-10 01:21 UTC by msadang

In CI folder the following changes have been made:

- Remove logger function and replace all logger calls with gpuci_logger

- Removed all ellipses ... from logger messages

- Prepend /opt to the conda path in PATH variable

- Replace conda with gpuci_conda_retry for build and install calls  (Did not replace conda activate with gpuci_conda_retry) 

- Replace source activate <env> with the following:
. /opt/conda/etc/profile.d/conda.sh
conda activate rapids

- Replace conda list with more verbose information:
conda info
conda config --show-sources
conda list --show-channel-urls

- Update Copyright year in the top of scripts to include 2020 if applicable

- Set PARALLEL_LEVEL to ${PARALLEL_LEVEL:-4}

- Set gpuci_conda_retry flags in cpu/build.sh
# Setup 'gpuci_conda_retry' for build retries (results in 2 total attempts)
export GPUCI_CONDA_RETRY_MAX=1
export GPUCI_CONDA_RETRY_SLEEP=30

- Replace calls to gcc and g++ with $CC and $CXX respectively

2020-11-10 01:21 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-11-10 16:01 UTC, ajschmidt8 requested changes
looks good so far. I found a few things that will need to be changed. Dillon's `rmm` PR below is a good reference (just ignore the project flash specific stuff).

https://github.com/rapidsai/rmm/pull/615/files

2020-11-10 16:10 UTC, dillon-cullinan requested changes

2020-11-10 16:10 UTC, dillon-cullinan commented on ci/local/README.md
> +$ conda activate rapids gdf    #Activate gpuCI conda environment
`gdf` should be removed here.

2020-11-13 18:48 UTC, msadang commented on ci/local/README.md
> +$ conda activate rapids gdf    #Activate gpuCI conda environment
gdf removed

2020-11-13 18:49 UTC, msadang commented
gpuci_logger and parallel level changed.

2020-11-16 19:24 UTC, ajschmidt8 approved these changes

2020-11-18 06:09 UTC, dillon-cullinan approved these changes

2020-12-16 22:22 UTC, merged